[package]
name = "naive-ocw-exploiter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subxt = "0.26.0"
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full", "bit-vec"] }
tokio = { version = "1.25", features = ["rt-multi-thread", "macros", "time"] }
sp-keyring = "12.0.0"
sp-core = { version = "11.0.0", default-features = false }
sp-runtime = { version = "12.0.0" }
tracing-subscriber = "0.3.11"

